# Generated by Django 3.2.4 on 2021-06-20 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exposicion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposicion',
            name='sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='exposicion', to='exposicion.sede'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleexposicion',
            name='exposicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalleExposicion', to='exposicion.exposicion'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='duracionExtendida',
            field=models.PositiveIntegerField(help_text='Duracion en minutos', verbose_name='Duracion extendida'),
        ),
    ]
