# Generated by Django 3.2.4 on 2021-06-19 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Gu', 'Guia')], max_length=2, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Lun', 'Lunes'), ('Mar', 'Martes'), ('Mie', 'Miercoles'), ('Jue', 'Jueves'), ('Vie', 'Viernes'), ('Sab', 'Sabado'), ('Dom', 'Domingo')], max_length=3, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaIngreso', models.TimeField(verbose_name='Hora de ingreso')),
                ('horaSalida', models.TimeField(verbose_name='Hora de salida')),
                ('diaSemana', models.ManyToManyField(to='empleado.DiaSemana')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.cargo')),
                ('horarioEmpleado', models.ManyToManyField(to='empleado.HorarioEmpleado')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
