# Generated by Django 3.2.4 on 2021-06-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='nombre',
            field=models.CharField(choices=[('Gu', 'Guia')], max_length=10, verbose_name='Nombre'),
        ),
    ]
